###############################################################################
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
global:
  openldap:
    replicaCount: 1

    image:
      # From repository https://github.com/osixia/docker-openldap
      repository: osixia/openldap
      tag: 1.2.4
      pullPolicy: IfNotPresent

    initResources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

    service:
      annotations: {}
      clusterIP: ""

      ldapPort: 389
      sslLdapPort: 636  # Only used if tls.enabled is true
      ## List of IP addresses at which the service is available
      ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
      ##
      externalIPs: []

      loadBalancerIP: ""
      loadBalancerSourceRanges: []
      type: ClusterIP

    # Default configuration for openldap as environment variables. These get injected directly in the container.
    # Use the env variables from https://github.com/osixia/docker-openldap#beginner-guide
    env:
      LDAP_ORGANISATION: "spm"
      LDAP_DOMAIN: "spm.com"
      LDAP_TLS: "true"
      LDAP_TLS_ENFORCE: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"

    # Default Passwords to use, stored as a secret. If unset, passwords are auto-generated.
    # You can override these at install time with
    # helm install openldap --set openldap.adminPassword=<passwd>,openldap.configPassword=<passwd>
    adminPassword: admin
    configPassword: config

    # Custom openldap configuration files used to override default settings
    # customLdifFiles:
      # 01-default-users.ldif: |-
        # Predefine users here

    # settings for enabling TLS
    tls:
      enabled: false
      secret: ""  # The name of a kubernetes.io/tls type secret to use for TLS
      CA:
        enabled: false
        secret: ""  # The name of a generic secret to use for custom CA certificate (ca.crt)

    ## Persist data to a persistent volume
    persistence:
      enabled: false
      ## database data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode: ReadWriteOnce
      size: 8Gi
      # existingClaim: ""

    ## Add additional labels to all resources
    extraLabels: {}

    ## Add additional annotations to pods
    podAnnotations: {}

# Define deployment strategy - IMPORTANT: use rollingUpdate: null when use Recreate strategy.
# It prevents from merging with existing map keys which are forbidden.
# strategy:
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0
  #
  # or
  #
  # type: Recreate
  # rollingUpdate: null
strategy: {}

# Spcifies an existing secret to be used for admin and config user passwords
existingSecret: ""

nodeSelector: {}

tolerations: []

affinity: {}

## test container details
test:
  enabled: false
  image:
    repository: dduportal/bats
    tag: 0.4.0
