###############################################################################
# Copyright 2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-messaging-config
  namespace: {{ .Release.Namespace }}
data:
  server_resources_messaging.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Placed by Kubernetes Configmap. -->
    <server description="Server Messaging (JMS) Resource Configuration">

      <featureManager>
        <feature>wmqJmsClient-2.0</feature>
        <feature>transportSecurity-1.0</feature>
      </featureManager>

      <messagingEngine>
        <queue id="QN.DPENACTMENT" forceReliability="ReliablePersistent" maxMessageDepth="5000" />
        <queue id="QN.DPERROR" forceReliability="ReliablePersistent" maxMessageDepth="5000" />
        <queue id="QN.WORKFLOWENACTMENT" forceReliability="ReliablePersistent" maxMessageDepth="5000" />
        <queue id="QN.WORKFLOWACTIVITY" forceReliability="ReliablePersistent" maxMessageDepth="5000" />
        <queue id="QN.WORKFLOWERROR" forceReliability="ReliablePersistent" maxMessageDepth="5000" />
        <queue id="QN.CURAMDEADMESSAGEQUEUE" forceReliability="ReliablePersistent" maxMessageDepth="5000" />
        <topicSpace id="Default.Topic.Space" forceReliability="ReliablePersistent" maintainStrictOrder="true" maxMessageDepth="5000" />
      </messagingEngine>

      <variable name="wmqJmsClient.rar.location" value="/opt/wmq/wmq.jmsra.rar"/>
      <variable name="mqHostName" value="${env.MQ_SERVICE_NAME}"/>
      <variable name="listenerPort" value="1414"/>
      <variable name="mqName" value="{{ $.Values.global.mq.queueManager.name | default "QM1" }}"/>
      <variable name="channel" value="MQ_CHN"/>

      <jmsActivationSpec id="eis/DPEnactmentAS">
        <properties.wmqJms destinationRef="DPEnactment" destinationType="javax.jms.Queue" hostName="${mqHostName}" port="${listenerPort}" queueManager="${mqName}" subscriptionDurability="Durable" />
      </jmsActivationSpec>

      <jmsQueue id="DPEnactment" jndiName="jms/DPEnactment">
        <properties.wmqJms persistence="PERS" baseQueueName="QN.DPENACTMENT" />
      </jmsQueue>

      <jmsActivationSpec id="eis/DPErrorAS">
        <properties.wmqJms destinationRef="DPError" destinationType="javax.jms.Queue" hostName="${mqHostName}" port="${listenerPort}" queueManager="${mqName}" subscriptionDurability="Durable" />
      </jmsActivationSpec>

      <jmsQueue id="DPError" jndiName="jms/DPError">
        <properties.wmqJms persistence="PERS" baseQueueName="QN.DPERROR" />
      </jmsQueue>

      <jmsActivationSpec id="eis/WorkflowEnactmentAS">
        <properties.wmqJms destinationRef="WorkflowEnactment" destinationType="javax.jms.Queue" hostName="${mqHostName}" port="${listenerPort}" queueManager="${mqName}" subscriptionDurability="Durable" />
      </jmsActivationSpec>

      <jmsQueue id="WorkflowEnactment" jndiName="jms/WorkflowEnactment">
        <properties.wmqJms persistence="PERS" baseQueueName="QN.WORKFLOWENACTMENT" />
      </jmsQueue>

      <jmsActivationSpec id="eis/WorkflowActivityAS">
        <properties.wmqJms destinationRef="WorkflowActivity" destinationType="javax.jms.Queue" hostName="${mqHostName}" port="${listenerPort}" queueManager="${mqName}" subscriptionDurability="Durable" />
      </jmsActivationSpec>

      <jmsQueue id="WorkflowActivity" jndiName="jms/WorkflowActivity">
        <properties.wmqJms persistence="PERS" baseQueueName="QN.WORKFLOWACTIVITY" />
      </jmsQueue>

      <jmsActivationSpec id="eis/WorkflowErrorAS">
        <properties.wmqJms destinationRef="WorkflowError" destinationType="javax.jms.Queue" hostName="${mqHostName}" port="${listenerPort}" queueManager="${mqName}" subscriptionDurability="Durable" />
      </jmsActivationSpec>

      <jmsQueue id="WorkflowError" jndiName="jms/WorkflowError">
        <properties.wmqJms persistence="PERS" baseQueueName="QN.WORKFLOWERROR" />
      </jmsQueue>

      <jmsActivationSpec id="eis/CuramDeadMessageQueueAS">
        <properties.wmqJms destinationRef="CuramDeadMessageQueue" destinationType="javax.jms.Queue" hostName="${mqHostName}" port="${listenerPort}" queueManager="${mqName}" subscriptionDurability="Durable" />
      </jmsActivationSpec>

      <jmsQueue id="CuramDeadMessageQueue" jndiName="jms/CuramDeadMessageQueue">
        <properties.wmqJms persistence="PERS" baseQueueName="QN.CURAMDEADMESSAGEQUEUE" />
      </jmsQueue>

      <jmsActivationSpec id="eis/CuramCacheInvalidationTopicAS">
        <properties.wmqJms destinationRef="CuramCacheInvalidationTopic" destinationType="javax.jms.Topic" hostName="${mqHostName}" port="${listenerPort}" queueManager="${mqName}" subscriptionDurability="Durable" />
      </jmsActivationSpec>

      <jmsActivationSpec id="Curam/InvalidationModule/CuramCacheInvalidationTopicMDB">
        <properties.wmqJms destinationRef="CuramCacheInvalidationTopic" destinationType="javax.jms.Topic" hostName="${mqHostName}" port="${listenerPort}" queueManager="${mqName}" subscriptionDurability="Durable" />
      </jmsActivationSpec>

      <jmsTopic id="CuramCacheInvalidationTopic" jndiName="jms/CuramCacheInvalidationTopic">
        <properties.wmqJms baseTopicName="CURAMCACHEINVALIDATIONTOPIC" />
      </jmsTopic>

      <jmsConnectionFactory id="CuramQueueConnectionFactory" jndiName="jms/CuramQueueConnectionFactory" connectionManagerRef="ConMgr6">
        <properties.wmqJms hostName="${mqHostName}" port="${listenerPort}" queueManager="${mqName}" channel="${channel}" sslCipherSuite="SSL_RSA_WITH_AES_128_CBC_SHA256" />
      </jmsConnectionFactory>
      <connectionManager id="ConMgr6" maxPoolSize="2"/>

      <jmsTopicConnectionFactory id="CuramTopicConnectionFactory" jndiName="jms/CuramTopicConnectionFactory">
        <properties.wmqJms hostName="${mqHostName}" port="${listenerPort}" queueManager="${mqName}" channel="${channel}" sslCipherSuite="SSL_RSA_WITH_AES_128_CBC_SHA256" />
      </jmsTopicConnectionFactory>

    </server>
