language: node_js
node_js:
  - "12"

group: bluezone
dist: xenial

install:
  - npm install -g gatsby markdownlint-cli
  - npm install

script:
  - markdownlint **/*.mdx --ignore src/pages/index.mdx
  - gatsby build --prefix-paths

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: public
    github_token: $GITHUB_TOKEN
    github_url: github.com
    committer_from_gh: true
    target_branch: gh-pages
    on:
      branch: master
