language: node_js
node_js:
  - "12"

group: bluezone
dist: xenial

install:
  - npm install -g gatsby markdownlint-cli
  - npm install

script:
  - markdownlint **/*.mdx
  - gatsby build --prefix-paths

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: public
    github_token: $GITHUB_TOKEN
    github_url: github.ibm.com
    committer_from_gh: true
    target_branch: gh-pages
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    local_dir: public
    repo: wh-curamspm-devops/vnext-assets
    github_token: $GITHUB_TOKEN
    github_url: github.ibm.com
    committer_from_gh: true
    target_branch: master
    on:
      branch: next-release
