version: '2.2'
services:
  ibmhttp:
    build: 
      context: .
      dockerfile: StaticContent.Dockerfile
      labels:
        InstallerBuildID: ${actualInstallerBuildId:-NotSet}
        CuramVersion: ${VERSION_VALUE}
        CuramConfiguration: ${CuramInstallation:-NotSet}
        Locale: ${Locale:-en_US}
        LangPacks: ${LangPacks:-None}
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    image: ${DOCKER_REGISTRY}/${CuramVersion}/${IMAGE_PREFIX:?'IMAGE_PREFIX' must be specified}_ihs:${IMAGE_TAG:-untagged}