###############################################################################
# Copyright 2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "spm.labels" . | indent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  {{- if or .Values.ingress.tlsSecretName .Values.ingress.generateCert }}
  tls:
    - hosts:
        -  {{ required "When ingress is enabled, you must provide a value for ingress.hostname" .Values.ingress.hostname }}
      {{- if .Values.ingress.generateCert }}
      secretName: {{ .Release.Name }}-tls
      {{- else }}
      secretName: {{ .Values.ingress.tlsSecretName }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          {{- range $name, $app := .Values.global.apps.config }}
          {{- if and $app.enabled $app.ingressPath }}
          - path: {{ $app.ingressPath }}
            backend:
              serviceName: {{ $.Release.Name }}-apps-{{ $name }}
              servicePort: {{ $.Values.global.apps.common.port }}
          {{- end }}
          {{- end }}
          - path: /CuramStatic
            backend:
              serviceName: {{ $.Release.Name }}-ihs
              servicePort: {{ $.Values.global.ihs.servicePort }}
{{- end }}
