###############################################################################
# Copyright 2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

global:
  images:
    registry: &imageRegistry minikube.local:5000
    pullPolicy: IfNotPresent
  database:
    type: "db2"
    hostname: "db2hostname"
    dbName: "DATABASE"
    username: "db2admin"
    password: "db2admin"
    spm_psw: "spmEncryptedDBPassword"
    wlp_psw: "xorEncodedDBPassword"
    ssl:
      enabled: false
      secretName: 'secretName'
  imagePullSecret:
    registry: *imageRegistry

batch:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 3
  ttlSecondsAfterFinished: 60
  backoffLimit: 5
  # programName: curam.healthcare.sl.intf.BulkICReassessment.process
  programName: ""

nameOverride: ""
fullnameOverride: ""
