{{- if and .Values.global.openldap.persistence.enabled (not .Values.global.openldap.persistence.existingClaim) }}
---
###############################################################################
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "openldap.fullname" . }}
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.global.openldap.extraLabels }}
{{ toYaml .Values.global.openldap.extraLabels | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.global.openldap.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.global.openldap.persistence.size | quote }}
{{- if .Values.global.openldap.persistence.storageClass }}
{{- if (eq "-" .Values.global.openldap.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.global.openldap.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
