---
global:
  license: '' # Set to 'accept' after reviewing all license agreements
  images:
    registry: &imageRegistry image-registry.openshift-image-registry.svc:5000
    imageLibrary: 'ocp'
    imagePrefix: ''
    imageTag: latest
    pullPolicy: Always
  imagePullSecret:
    registry: *imageRegistry
    username: kubeadmin
    password:
  database:
    hostname: 192.168.0.32
  ceApp:
    imageLibrary: ''
    imageName: ''
    imageTag: latest
  apps:
    common:
      initialDelaySeconds: 60
      security:
        username: SYSTEM
    config:
      curam:
        enabled: true
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 2Gi
      rest:
        enabled: false
      citizenportal:
        enabled: false
      curamwebservices:
        enabled: false
      curambirtviewer:
        enabled: false
  isam:
    enabled: false
  ingress:
    enabled: true
    tlsSecretName: testkube-tls
    generateCert: true
    hostname: spm-ocp.apps-crc.testing