###############################################################################
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ltpa-keys-cm
  namespace: {{ .Release.Namespace }}
data:
  ltpa.keys: |
    # Placed by Kubernetes Configmap
    com.ibm.websphere.CreationDate=Mon Oct 8 08\:08\:08 UTC 2019
    com.ibm.websphere.CreationHost=localhost
    com.ibm.websphere.ltpa.version=1.0
    com.ibm.websphere.ltpa.Realm=defaultRealm
    com.ibm.websphere.ltpa.3DESKey={{ .Values.global.commonAppConfig.ltpa.encryptKey }}
    com.ibm.websphere.ltpa.PrivateKey={{ .Values.global.commonAppConfig.ltpa.privateKey }}
    com.ibm.websphere.ltpa.PublicKey={{ .Values.global.commonAppConfig.ltpa.publicKey }}
