###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2019. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sessions-cm
  namespace: {{ .Release.Namespace }}
data:
  sessions_management.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Placed by Kubernetes Configmap. -->
    <server description="Server Session Management Configuration">
      <featureManager>
        <feature>sessionDatabase-1.0</feature>
      </featureManager>

      <dataSource id="curamsessdb" jndiName="jdbc/curamsessdb"
        jdbcDriverRef="CuramJdbcDriver" type="javax.sql.XADataSource">
        isolationLevel="TRANSACTION_READ_COMMITTED"
      >
        {{- include "configmaps.dsprops.fragment" . | nindent 8 }}
      </dataSource>

      <httpSessionDatabase
        id="SessionDB"
        dataSourceRef="curamsessdb"
        {{- if eq (.Values.global.database.type | upper) "DB2" }}
        db2RowSize="32KB"
        {{- end }}
        tableName="WLP_SESSION"
        skipIndexCreation="true"
      />
      <httpSession
        storageRef="SessionDB"
        cloneId="${env.HOSTNAME}"
        idReuse="true"
        maxInMemorySessionCount="${httpSession.maxInMemorySessionCount}"
        cookieSecure="true"
      />
    </server>
