{{- with .Values.global.xmlserver }}
---
###############################################################################
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xmlserver.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "xmlserver.labels" $ | indent 4 }}
spec:
  replicas: {{ .replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "xmlserver.fullname" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "xmlserver.fullname" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      {{- if .runAs }}
      securityContext:
        runAsUser: {{ .runAs }}
      {{- end }}
      {{- if $.Values.global.imagePullSecret.username }}
      imagePullSecrets:
        - name: {{ $.Release.Name }}-pull-secret
      {{- end }}
      restartPolicy: {{ .restartPolicy | default "Always" }}
      initContainers:
        - name: wait-db2
          image: busybox:1.28
          command:
            - /bin/sh
            - -c
            - >
              until nslookup {{ include "xmlserver.dbhostname" $ }}; do
                echo waiting for {{ include "xmlserver.dbhostname" $ }} to be available...;
                sleep 2;
              done
      containers:
        - name: {{ $.Chart.Name }}
          image: {{ include "xmlserver.imageFullName" $.Values.global.images }}
          imagePullPolicy: {{ $.Values.global.images.pullPolicy }}
          ports:
            - containerPort: {{ .port | default 1800 }}
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{ end }}
