{{- with .Values.global.xmlserver }}
---
###############################################################################
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: v1
kind: Service
metadata:
  name: {{ include "xmlserver.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "xmlserver.labels" $ | indent 4 }}
spec:
  type: {{ .serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .port | default 1800 }}
      targetPort: {{ .port | default 1800 }}
  selector:
    app.kubernetes.io/name: {{ include "xmlserver.fullname" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{ end }}
